export default {
  WIZARDS_FORM_DATA: 'WIZARDS_FORM_DATA',
  PERSONAL_DETAILS: 'PERSONAL_DETAILS',
  BANK_DETAILS: 'BANK_DETAILS',
  LENDERS_DETAILS: 'LENDERS_DETAILS',
  PRODUCT_ID: 'PRODUCT_ID',
  USER_TOKEN: 'USER_TOKEN',
  XAPPLICATIONID: 'XAPPLICATIONID',
  PRODUCTDATA: 'PRODUCTDATA',
  FINANCE_APPLICATION: 'FINANCE_APPLICATION'
}